// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Filters() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = filterForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func filterForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main id=\"filter-form\"><section id=\"variants\"><label for=\"variants-input\">Variants</label> <input type=\"text\" id=\"variants-input\" name=\"variants\" placeholder=\"1oz,1g\"></section><section id=\"subcategory\"><label for=\"subcategory-input\">Subcategory</label> <input type=\"text\" id=\"subcategory-input\" name=\"sub\" placeholder=\"cartridges\"></section><section id=\"minPrice\"><label for=\"minPrice-input\">Min Price</label> <input type=\"text\" id=\"minPrice-input\" name=\"min_price\" placeholder=\"0\"></section><section id=\"maxPrice\"><label for=\"maxPrice-input\">Max Price</label> <input type=\"text\" id=\"maxPrice-input\" name=\"max_price\" placeholder=\"100\"></section><section id=\"excluded-brands\"><label for=\"excluded-brands-input\">Excl. Brands</label> <input type=\"text\" id=\"excluded-brands-input\" name=\"not_brands\" placeholder=\"brand1,brand2\"></section><section id=\"included-brands\"><label for=\"included-brands-input\">Incl. Brands</label> <input type=\"text\" id=\"included-brands-input\" name=\"brands\" placeholder=\"brand1,brand2\"></section><section id=\"excluded-terms\"><label for=\"excluded-terms-input\">Excl. Terms</label> <input type=\"text\" id=\"excluded-terms-input\" name=\"exclude\" placeholder=\"term1,term2\"></section><section id=\"included-terms\"><label for=\"included-terms-input\">Incl. Terms</label> <input type=\"text\" id=\"included-terms-input\" name=\"include\" placeholder=\"term1,term2\"></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
